### ISSUE TITLE
打不开

### ISSUE THREAD

**Issue by fashiye** [DoctorReid/StarRailAutoProxy#166]
Traceback (most recent call last):
  File "paddle\fluid\core.py", line 269, in <module>
    from . import libpaddle
ImportError: DLL load failed while importing libpaddle: 动态链接库(DLL)初始化例程失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui\app.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "gui\log_view.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "gui\sr_basic_view.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "sr\context.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "sr\image\cn_ocr_matcher.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "paddleocr\paddleocr.py", line 21, in <module>
    import paddle
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "paddle\__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "paddle\framework\random.py", line 17, in <module>
    from paddle import fluid
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "paddle\fluid\core.py", line 343, in <module>
    sys.stderr.write(
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by DoctorReid** [comment]
这种感觉是跟你的windows系统不兼容。。目前还没有遇到过，不知道怎么解决

**Comment by fashiye** [comment]
win10不至于不兼容吧，专业版

**Comment by DoctorReid** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/11156

PaddleOCR处也没有找到对应解决方法。你是用源码运行还是打包的exe运行

**Comment by fashiye** [comment]
exe

**Comment by fashiye** [comment]
是不是因为我显卡太老了gtx 550 ti

**Comment by fashiye** [comment]
> 请检测你的机器cpu是否支持AVX指令 cat /proc/cpuinfo | grep -i avx，paddlepaddle2.5以及之后，不在支持noavx设备。
> 
> 如果不支持请根据以下进行安装，具体文档可参考[官方说明](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4/install/pip/linux-pip.html) 首先使用如下命令将 wheel 包下载到本地： cpu、mkl 版本 noavx 机器安装： python3 -m pip download paddlepaddle==2.4.2 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps cpu、openblas 版本 noavx 机器安装： python3 -m pip download paddlepaddle==2.4.2 -f https://www.paddlepaddle.org.cn/whl/linux/openblas/noavx/stable.html --no-index --no-deps

我u确实不支持

**Comment by fashiye** [comment]
不支持avx指令集

**Comment by DoctorReid** [comment]
应该是cpu的问题。不好意思了，不在我能力范围修改范围

**Comment by soloopooo** [comment]
> 应该是cpu的问题。不好意思了，不在我能力范围修改范围

我今天遇到了相同的问题，我CPU是i5-13600K，查找后发现是主板没有开启avx导致，如果确认自己的CPU是intel 2代i5以上的，有极大可能是因为主板把AVX/AVX2功能关了。解决方法就是在主板设置里把AVX/AVX2相关功能开启
