### ISSUE TITLE
开始后报错

### ISSUE THREAD

**Issue by lewyi** [DoctorReid/StarRailAutoProxy#69]
[DEBUG 2023-10-27 16:08:47,456 on_key_press:51] 触发按键 f10
[16:08:47] [stop_running 65] [INFO]: 停止运行
[INFO 2023-10-27 16:08:47,458 stop_running:65] 停止运行
[DEBUG 2023-10-27 16:08:47,460 log_all_performance:77] [analyse_mini_map] 次数: 0 平均耗时: 0.000000 最高耗时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:08:47,460 log_all_performance:78] [cal_character_pos_by_sp_result] 次数: 0 平均耗时: 0.000000 最高耗时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:08:47,460 log_all_performance:79] [cal_character_pos_by_feature_match] 次数: 0 平均耗时: 0.000000 最高耗时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:08:47,461 log_all_performance:80] [cal_character_pos_by_road_mask] 次数: 0 平均耗时: 0.000000 最高耗时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:08:47,461 log_all_performance:81] [cal_character_pos_by_original] 次数: 0 平均耗时: 0.000000 最高耗
时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:08:52,107 on_key_press:51] 触发按键 f9
[DEBUG 2023-10-27 16:09:42,515 on_key_press:51] 触发按键 f9
[DEBUG 2023-10-27 16:09:43,467 on_key_press:51] 触发按键 f10
[16:09:43] [stop_running 65] [INFO]: 停止运行
[INFO 2023-10-27 16:09:43,467 stop_running:65] 停止运行
[DEBUG 2023-10-27 16:09:43,468 log_all_performance:77] [analyse_mini_map] 次数: 0 平均耗时: 0.000000 最高耗时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:09:43,468 log_all_performance:78] [cal_character_pos_by_sp_result] 次数: 0 平均耗时: 0.000000 最高耗时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:09:43,468 log_all_performance:79] [cal_character_pos_by_feature_match] 次数: 0 平均耗时: 0.000000 最高耗时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:09:43,468 log_all_performance:80] [cal_character_pos_by_road_mask] 次数: 0 平均耗时: 0.000000 最高耗时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:09:43,468 log_all_performance:81] [cal_character_pos_by_original] 次数: 0 平均耗时: 0.000000 最高耗 时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:09:47,462 on_key_press:51] 触发按键 f9
[DEBUG 2023-10-27 16:09:47,797 on_key_press:51] 触发按键 f9
[DEBUG 2023-10-27 16:09:47,977 on_key_press:51] 触发按键 f9
[16:09:48] [execute 15] [INFO]: 加载工具中
[INFO 2023-10-27 16:09:48,605 execute:15] 加载工具中
[16:09:48] [init_image_matcher 124] [INFO]: 加载图片匹配器完毕
[INFO 2023-10-27 16:09:48,605 init_image_matcher:124] 加载图片匹配器完毕
[16:09:48] [init_ocr_matcher 132] [INFO]: 加载OCR识别器完毕
[INFO 2023-10-27 16:09:48,809 init_ocr_matcher:132] 加载OCR识别器完毕
[16:09:48] [init_controller 116] [INFO]: 加载游戏控制器完毕
[INFO 2023-10-27 16:09:48,812 init_controller:116] 加载游戏控制器完毕
[16:09:48] [execute 19] [INFO]: 加载工具完毕
[INFO 2023-10-27 16:09:48,813 execute:19] 加载工具完毕
[16:09:48] [active 50] [ERROR]: 切换到游戏窗口失败 可尝试手动切换到游戏窗口中 3秒后脚本启动
Traceback (most recent call last):
  File "basic\win_utils.py", line 45, in active_win
  File "pygetwindow\_pygetwindow_win.py", line 246, in activate
  File "pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
pygetwindow.PyGetWindowException: Error code from Windows: 5 - Access is denied.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sr\win.py", line 48, in active
  File "basic\win_utils.py", line 49, in active_win
  File "pygetwindow\_pygetwindow_win.py", line 246, in activate
  File "pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
pygetwindow.PyGetWindowException: Error code from Windows: 5 - Access is denied.
[ERROR 2023-10-27 16:09:48,813 active:50] 切换到游戏窗口失败 可尝试手动切换到游戏窗口中 3秒后脚本启动
Traceback (most recent call last):
  File "basic\win_utils.py", line 45, in active_win
  File "pygetwindow\_pygetwindow_win.py", line 246, in activate
  File "pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
pygetwindow.PyGetWindowException: Error code from Windows: 5 - Access is denied.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sr\win.py", line 48, in active
  File "basic\win_utils.py", line 49, in active_win
  File "pygetwindow\_pygetwindow_win.py", line 246, in activate
  File "pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
pygetwindow.PyGetWindowException: Error code from Windows: 5 - Access is denied.
[16:09:52] [init_app 136] [INFO]: 共加载 43 条线路
[INFO 2023-10-27 16:09:52,318 init_app:136] 共加载 43 条线路
[16:09:52] [init_app 139] [INFO]: 之前已完成线路 0 条
[INFO 2023-10-27 16:09:52,319 init_app:139] 之前已完成线路 0 条
[ WARN:0@72.497] global loadsave.cpp:248 cv::findDecoder imread_('C:\Users\lewyi\OneDrive\妗岄潰\StarR[16:09:52] [run_one_route 178] [INFO]: 准备执行线路 <sr.app.world_patrol.WorldPatrolRouteId object at 0x000001BDB755CC50> 空间站黑塔 基座舱 段 监控室
ailAutoProxy-v0.4.0\dist\StarRailAutoP[INFO 2023-10-27 16:09:52,322 run_one_route:178] 准备执行线路 <sr.app.world_patrol.WorldPatrolRouteId object at 0x000001BDB755CC50> 空间站黑塔 基座舱段 监控室
roxy\_internal\images\[16:09:52] [run_one_route 179] [INFO]: 感谢以下人员提供本路线 ['DoctorReid']
template\mm_tp_01\origin.png'[INFO 2023-10-27 16:09:52,323 run_one_route:179] 感谢以下人员提供本路线 ['DoctorReid']
): can't open/r[16:09:52] [run_one_route 184] [INFO]: 准备传送 空间站黑塔 基座舱段 监控室
ead file: check file path/integrity
[INFO 2023-10-27 16:09:52,324 run_one_route:184] 准备传送 空间站黑塔 基座舱段 监控室
[ WARN:0@72.501] global loadsave.cpp:248 cv::findDecoder imread_('C:\Users\lewyi\OneDrive\妗岄潰\StarRailAutoProxy-v0.4.0\dist\StarRailAutoProxy\_internal\images\template\mm_tp_01\gray.png'): can't open/read file: check file path/integrity
[ WARN:1@72.501] global loadsave.cpp:248 cv::findDecoder imread_('C:\Users\lewyi\OneDrive\妗岄潰\StarRailAutoProxy-v0.4.0\dist\StarRailAutoProxy\_internal\images\map\P01_KJZHT\R02_JZCD\origin.png'): can't open/read file: check file path/integrity
[ WARN:0@72.505] global loadsave.cpp:248 cv::findDecoder imread_('C:\Users\lewyi\OneDrive\妗岄潰\StarRailAutoProxy-v0.4.0\dist\StarRailAutoProxy\_internal\images\template\mm_tp_01\mask.png'): can't open/read file: check file path/integrity
[ WARN:1@72.508] global loadsave.cpp:248 cv::findDecoder imread_('C:\Users\lewyi\OneDrive\妗岄潰\StarRailAutoProxy-v0.4.0\dist\StarRailAutoProxy\_internal\images\map\P01_KJZHT\R02_JZCD\gray.png'): can't open/read file: check file path/integrity
[ERROR:0@72.511] global persistence.cpp:512 cv::FileStorage::Impl::open Can't open file: 'C:\Users\lewyi\OneDrive\妗岄潰\StarRailAutoProxy-v0.4.0\dist\StarRailAutoProxy\_internal\images\template\mm_tp_01\features.xml' in read mode
[ WARN:1@Exception in thread Thread-36 (preheat):
7Traceback (most recent call last):
2  File "threading.py", line 1045, in _bootstrap_inner
.514] global loadsav  File "threading.py", line 982, in run
e.cpp:248 cv::find  File "sr\app\world_patrol.py", line 155, in preheat
Decoder imr  File "sr\image\image_holder.py", line 151, in preheat_for_world_patrol
ead_('C:\Users\lewyi\OneDrive\妗岄潰\StarRailAutoProxy-v0.4.0\dist\StarRailAutoPro  File "sr\image\image_holder.py", line 126, in get_template
xy\_internal\i  File "sr\image\image_holder.py", line 83, in load_template
mages\map\P01  File "basic\img\cv2_utils.py", line 250, in feature_keypoints_from_np
_KJZHT\R02_JZCD\mask.png'): can't open/read fiTypeError: 'NoneType' object is not iterable
le: check file path/integrity
[ERROR:1@72.522] global persistence.cpp:512 cv::FileStorage::Impl::open Can't open file: 'C:\Users\lewyi\OneDrive\妗岄潰\StarRailAutoProxy-v0.4.0\dist\StarRailAutoProxy\_internal\images\map\P01_KJZHT\R02_JZCD\features.xml' in read mode
[16:09:52] [execute 51] [ERROR]: 指令执行出错
Traceback (most recent call last):
  File "sr\operation\__init__.py", line 44, in execute
  File "sr\app\world_patrol.py", line 167, in run
  File "sr\app\world_patrol.py", line 185, in run_one_route
  File "sr\operation\combine\transport.py", line 27, in __init__
  File "sr\operation\unit\choose_transport_point.py", line 26, in __init__
  File "sr\image\image_holder.py", line 61, in get_large_map
  File "sr\image\image_holder.py", line 35, in load_large_map
  File "basic\img\cv2_utils.py", line 250, in feature_keypoints_from_np
TypeError: 'NoneType' object is not iterable
[ERROR 2023-10-27 16:09:52,349 execute:51] 指令执行出错
Traceback (most recent call last):
  File "sr\operation\__init__.py", line 44, in execute
  File "sr\app\world_patrol.py", line 167, in run
  File "sr\app\world_patrol.py", line 185, in run_one_route
  File "sr\operation\combine\transport.py", line 27, in __init__
  File "sr\operation\unit\choose_transport_point.py", line 26, in __init__
  File "sr\image\image_holder.py", line 61, in get_large_map
  File "sr\image\image_holder.py", line 35, in load_large_map
  File "basic\img\cv2_utils.py", line 250, in feature_keypoints_from_np
TypeError: 'NoneType' object is not iterable
[16:09:52] [run_one_route 178] [INFO]: 准备执行线路 <sr.app.world_patrol.WorldPatrolRouteId object at 0x000001BDB6D725D0> 空间站黑塔 收容舱段 毁灭之蕾
[INFO 2023-10-27 16:09:52,353 run_one_route:178] 准备执行线路 <sr.app.world_patrol.WorldPatrolRouteId object at 0x000001BDB6D725D0> 空间站黑塔 收容舱段 毁灭之蕾
[16:09:52] [run_one_route 179] [INFO]: 感谢以下人员提供本路线 ['DoctorReid']
[INFO 2023-10-27 16:09:52,355 run_one_route:179] 感谢以下人员提供本路线 ['DoctorReid']
[16:09:52] [run_one_route 184] [INFO]: 准备传送 空间站黑塔 收容舱段 毁灭之蕾
[INFO 2023-10-27 16:09:52,355 run_one_route:184] 准备传送 空间站黑塔 收容舱段 毁灭之蕾
[ WARN:1@72.534] global loadsave.cpp:248 cv::findDecoder imread_('C:\Users\lewyi\OneDrive\妗岄潰\StarRailAutoProxy-v0.4.0\dist\StarRailAutoProxy\_internal\images\map\P01_KJZHT\R03_SRCD_L1\raw.png'): can't open/read file: check file path/integrity
[ WARN:1@72.538] global loadsave.cpp:248 cv::findDecoder imread_('C:\Users\lewyi\OneDrive\妗岄潰\StarRailAutoProxy-v0.4.0\dist\StarRailAutoProxy\_internal\images\map\P01_KJZHT\R03_SRCD_L1\origin.png'): can't open/read file: check file path/integrity
[ WARN:1@72.543] global loadsave.cpp:248 cv::findDecoder imread_('C:\Users\lewyi\OneDrive\妗岄潰\StarRailAutoProxy-v0.4.0\dist\StarRailAutoProxy\_internal\images\map\P01_KJZHT\R03_SRCD_L1\gray.png'): can't open/read file: check file path/integrity
[ WARN:1@72.548] global loadsave.cpp:248 cv::findDecoder imread_('C:\Users\lewyi\OneDrive\妗岄潰\StarRailAutoProxy-v0.4.0\dist\StarRailAutoProxy\_internal\images\map\P01_KJZHT\R03_SRCD_L1\mask.png'): can't open/read file: check file path/integrity
[ERROR:1@72.553] global persistence.cpp:512 cv::FileStorage::Impl::open Can't open file: 'C:\Users\lewyi\OneDrive\妗岄潰\StarRailAutoProxy-v0.4.0\dist\StarRailAutoProxy\_internal\images\map\P01_KJZHT\R03_SRCD_L1\features.xml' in read mode
[16:09:52] [execute 51] [ERROR]: 指令执行出错
Traceback (most recent call last):
  File "sr\operation\__init__.py", line 44, in execute
  File "sr\app\world_patrol.py", line 167, in run
  File "sr\app\world_patrol.py", line 185, in run_one_route
  File "sr\operation\combine\transport.py", line 27, in __init__
  File "sr\operation\unit\choose_transport_point.py", line 26, in __init__
  File "sr\image\image_holder.py", line 61, in get_large_map
  File "sr\image\image_holder.py", line 35, in load_large_map
  File "basic\img\cv2_utils.py", line 250, in feature_keypoints_from_np
TypeError: 'NoneType' object is not iterable
[ERROR 2023-10-27 16:09:52,379 execute:51] 指令执行出错
Traceback (most recent call last):
  File "sr\operation\__init__.py", line 44, in execute
  File "sr\app\world_patrol.py", line 167, in run
  File "sr\app\world_patrol.py", line 185, in run_one_route
  File "sr\operation\combine\transport.py", line 27, in __init__
  File "sr\operation\unit\choose_transport_point.py", line 26, in __init__
  File "sr\image\image_holder.py", line 61, in get_large_map
  File "sr\image\image_holder.py", line 35, in load_large_map
  File "basic\img\cv2_utils.py", line 250, in feature_keypoints_from_np
TypeError: 'NoneType' object is not iterable
[16:09:52] [stop_running 65] [INFO]: 停止运行
[INFO 2023-10-27 16:09:52,381 stop_running:65] 停止运行
[16:09:52] [switch 80] [INFO]: 暂停运行
[INFO 2023-10-27 16:09:52,381 switch:80] 暂停运行
[DEBUG 2023-10-27 16:09:52,386 log_all_performance:77] [analyse_mini_map] 次数: 0 平均耗时: 0.000000 最高耗时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:09:52,388 log_all_performance:78] [cal_character_pos_by_sp_result] 次数: 0 平均耗时: 0.000000 最高耗时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:09:52,388 log_all_performance:79] [cal_character_pos_by_feature_match] 次数: 0 平均耗时: 0.000000 最高耗时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:09:52,388 log_all_performance:80] [cal_character_pos_by_road_mask] 次数: 0 平均耗时: 0.000000 最高耗时: 0.000000, 最低耗时: 999.000000
[DEBUG 2023-10-27 16:09:52,388 log_all_performance:81] [cal_character_pos_by_original] 次数: 0 平均耗时: 0.000000 最高耗 时: 0.000000, 最低耗时: 999.000000

**Comment by DoctorReid** [comment]
@lewyi 尝试管理员权限运行脚本

**Comment by lewyi** [comment]
@DoctorReid 还是一样

**Comment by DoctorReid** [comment]
> @DoctorReid 还是一样

新的错误日志中有 ```pygetwindow.PyGetWindowException: Error code from Windows: 5 - Access is denied.``` 这段吗？

那可能是这里，C:\Users\lewyi\OneDrive\```妗岄潰```\StarRailAutoProxy 文件夹用了中文名称，改成英文的试试

**Comment by lewyi** [comment]
@DoctorReid 可以了谢谢你

**Comment by DoctorReid** [comment]
> @DoctorReid 可以了谢谢你

觉得好的话可以点个star 嘿嘿

**Comment by DoctorReid** [comment]
目前脚本路径仅支持英文 暂时不打算优化
